/**
 * UNREVIEWED MACHINE DRAFT — Japanese web-console dictionary.
 * Exports: jaMessages, checked against the English message key set.
 * Deps: plural helper and the shared locale contracts.
 */
import { plural } from './plural';
import type { LocaleDictionary, MessageParams } from './types';
import type { MessageKey } from './en';
const n = (p: MessageParams): number => Number(p.count ?? 0);
export const jaMessages = {
 'form.noDescription':'説明なし','form.copy':'コピー','form.copied':'コピー済み',
 'app.title':'hiboss コンソール','app.loading':'コンソールを読み込み中…','brand.console':'コンソール','brand.subtitle':'boss サーバーに接続','language.label':'言語','language.en':'English','language.zh':'簡体字中国語','language.ja':'日本語','language.ko':'韓国語',
 'nav.aria':'コンソールモジュール','nav.dashboard':'ダッシュボード','nav.messages':'メッセージ','nav.sessions':'セッション','nav.agents':'エージェント','nav.groups':'グループ','nav.bosses':'Boss とアクセス','nav.routing':'ルーティング','nav.channels':'チャンネル','nav.audit':'監査','nav.system':'システム / Doctor',
 'nav.short.dashboard':'概要','nav.short.messages':'メッセージ','nav.short.sessions':'セッション','nav.short.agents':'エージェント','nav.short.groups':'グループ','nav.short.bosses':'アクセス','nav.short.routing':'ルーティング','nav.short.channels':'チャンネル','nav.short.audit':'監査','nav.short.system':'システム',
 'top.connected':'接続済み','top.offline':'オフライン','top.signOut':'サインアウト','common.refresh':'更新','common.retry':'再試行','common.close':'閉じる','common.dismiss':'閉じる','common.cancel':'キャンセル','common.create':'作成','common.creating':'作成中…','common.save':'設定を保存','common.saving':'保存中…','common.apply':'適用','common.delete':'削除','common.deleting':'削除中…','common.add':'追加','common.remove':'削除','common.previous':'前へ','common.next':'次へ','common.nothing':'まだありません','common.all':'すべて','common.dataWillAppear':'エージェントが報告を開始するとデータが表示されます。','common.requestFailed':'リクエストに失敗しました','common.never':'なし','common.unknown':'不明','common.optional':'任意','common.selectAgent':'エージェントを選択…','common.selectGroup':'グループを選択…','common.selectOwner':'所有者を選択…','common.selectTarget':'対象を選択','common.noLimit':'制限なし',
 'common.members':(p:MessageParams)=>plural(n(p),'ja',{other:`${n(p)} メンバー`}),'common.agents':(p:MessageParams)=>plural(n(p),'ja',{other:`${n(p)} エージェント`}),'common.channels':(p:MessageParams)=>plural(n(p),'ja',{other:`${n(p)} チャンネル`}),'common.loaded':(p:MessageParams)=>`${p.total??0} 件中 ${p.loaded??0} 件を読み込み済み`,'common.filtered':(p:MessageParams)=>`絞り込み ${p.count??0} 件`,'common.latestDirections':'最新 10 件 · 全方向',
 'page.dashboard':'ダッシュボード','page.dashboardSub':'概要 — リアルタイム KPI、チャンネルの状態、最近の通信','page.priorityDistribution':'優先度の分布','page.last24h':'過去 24 時間','page.sessionStatus':'セッション状態','page.seenLast24h':'過去 24 時間に確認','page.channelHealth':'チャンネル状態','page.configuredPaths':'設定済みの配信経路','page.recentMessages':'最近のメッセージ','page.noRecentMessages':'最近のメッセージはありません','page.noRecentMessagesDetail':'エージェントが更新を送信するとここに表示されます。','page.activeSessions':'アクティブなセッション','page.working':(p:MessageParams)=>`${p.count??0} 件が実行中`,'page.pendingDecisions':'保留中の判断','page.pendingDecisionsHint':'選択待ちのオプションメッセージ','page.blockingPending':'保留中のブロック','page.blockingPendingHint':'あなたの対応を待つエージェント','page.unread1h':'未読（1 時間）','page.unread1hHint':'エージェント → boss、未読',
 'page.agents':'エージェント','page.agentsSub':'エージェント — 一覧、識別情報、編集可能な設定','page.noAgents':'エージェントはありません','page.noAgentsDetail':'この boss がアクセスできるエージェントは許可後に表示されます。','page.groups':'グループ','page.groupsSub':'エージェントグループ — 一覧と全員へのブロードキャスト','page.noGroups':'グループはまだありません','page.noGroupsDetail':'アクセス可能なエージェントが所有するグループを作成してください。','page.bosses':'Boss とアクセス','page.bossesSub':'アクセス — boss の役割、チャンネルバインディング、エージェントアクセスマトリクス','page.noBosses':'Boss はまだありません','page.noBossesDetail':'役割、バインディング、エージェントアクセスを管理する boss を作成してください。','page.noAgentsInScope':'対象範囲にエージェントがありません — アクセス可能になると許可列が表示されます。',
 'page.routing':'ルーティング','page.routingSub':'ルーティングルール — 優先度テーブルと正規表現マッチャー','page.noRouting':'ルーティングルールはありません','page.noRoutingDetail':'正規表現ルールを追加するか、エージェントが定義するまで待ってください。','page.channels':'チャンネル','page.channelsSub':'チャンネル — エージェント別の接続ボード','page.noChannels':'設定済みのチャンネルはありません','page.noChannelsDetail':'hiboss CLI で Discord、Telegram、メール、または API 配信を設定します。秘密情報はここに表示されません。','page.audit':'監査','page.auditSub':'監査 — 検索可能な操作と配信のログ','page.noAudit':'監査エントリはありません','page.noAuditDetail':'エージェントや boss がシステムを操作すると記録されます。','page.noAuditSearch':'検索に一致する行はありません','page.noAuditSearchDetail':'ページ検索を消すか操作者/操作フィルターを広げてから適用してください。',
 'page.sessions':'セッション','page.sessionsSub':'セッション — 状態別エージェントセッションのカンバン','page.noSessions':'セッションはありません','page.noSessionsDetail':'アクティブなエージェントセッションは報告後に表示されます。','page.messages':'メッセージ','page.messagesSub':'メッセージ — 全ストリーム、フィルター、セッション分け、詳細ドロワー','page.noMessageMatch':'一致するメッセージはありません','page.noMessageMatchDetail':'方向を広げる、優先度チップを消す、別の語を検索する、を試してください。','page.loadMore':(p:MessageParams)=>`さらに読み込む（${p.count??0}）`,'page.bySession':'セッション別','page.flat':'フラット','page.checking':'確認中…','page.rerunChecks':'チェックを再実行','page.system':'システム / Doctor','page.systemSub':'システム — 接続セルフチェック、チャンネル状態、ライブ統計','page.seenRecently':'最近確認','page.noChannelRows':'チャンネル行が返されませんでした。',
 'connect.serverUrl':'サーバー URL','connect.bossToken':'Boss token','connect.connect':'接続','connect.connecting':'接続中…','connect.storedHint':'Token はこのブラウザーだけに保存されます（localStorage）。','form.name':'名前','form.role':'役割','form.telegramId':'Telegram ID','form.discordId':'Discord ID','form.description':'説明','form.ownerAgent':'所有者エージェント','form.targetAgent':'対象エージェント','form.channel':'チャンネル','form.pattern':'パターン','form.regexPattern':'正規表現パターン','form.priority':'優先度','form.createBoss':'boss を作成','form.createGroup':'グループを作成','form.addRule':'ルールを追加','form.bossName':'Boss 名','form.groupName':'グループ名','form.noAgentsGroup':'利用可能なエージェントがありません — 接続してからグループを作成してください。','form.noAgentsRule':'利用可能なエージェントがありません — アクセスを許可してからルールを追加してください。','form.createRule':'作成','form.addRoute':'ルートを追加','form.removeRoute':'ルートを削除',
 'form.agentConfig':'エージェント設定','form.config':'設定','form.configDetail':'このエージェントのデフォルト優先度、レート制限、チャンネルルーティング。','form.defaultPriority':'デフォルト優先度','form.rateLimit':'レート制限','form.channelRouting':'チャンネルルーティング','form.noRoutes':'ルートはありません — キーはチャンネルに対応します（例: critical → discord）。','form.saveConfig':'設定を保存','form.replyEmpty':'返信本文が空です','form.writeReply':'返信を書く…','form.sendReply':'返信を送信','form.forward':'転送','form.sending':'送信中…','form.sendBroadcast':'ブロードキャストを送信','form.broadcasting':'送信中…','form.broadcastTo':(p:MessageParams)=>`${p.name??''} にブロードキャスト…`,'form.writeBroadcast':'グループブロードキャストを書く…','form.broadcast':'ブロードキャスト','form.broadcastDetail':'グループブロードキャスト — グループの全メンバーにメッセージを送信',
 'form.members':'メンバー','form.memberEditor':'グループメンバーエディター','form.addMember':'メンバーを追加','form.removeMember':'メンバーを削除','form.hideMembers':'メンバーを隠す','form.editMembers':'メンバーを編集','form.deleteGroupConfirm':(p:MessageParams)=>`グループ「${p.name??''}」を削除しますか？元に戻せません。`,'form.endpointUnavailable':'エンドポイントは利用できません','form.sendCommand':'コマンドを送信','form.sendCommandDetail':'近日対応 — boss API にはセッション送信エンドポイントがまだありません（例として必要なのは','form.recentMessages':'最近のメッセージ','form.sessionNoTraffic':'このセッションには最近の通信がありません。','form.messageOptions':'メッセージオプション','form.options':'オプション','form.optionsExpired':'オプションの期限切れ','form.react':'リアクション','form.messageDetail':'メッセージ詳細','form.sessionDetail':'セッション詳細','form.agentDetail':'エージェント詳細','form.created':'作成','form.updated':'更新','form.expires':'期限','form.lastSeen':'最終確認','form.started':'開始','form.branch':'ブランチ','form.cwd':'作業ディレクトリ','form.id':'ID','form.authenticatedBoss':'認証済み boss','form.serverTime':'サーバー時刻','form.apiLatency':'API レイテンシ','form.notVerified':'未確認','form.database':'データベース','form.apiMe':'API /me','form.auditLog':'監査ログ','form.auditPagination':'監査ログのページネーション','form.when':'日時','form.actor':'アクター','form.action':'操作','form.resource':'リソース','form.details':'詳細',
 'form.actorType':'アクター種別','form.pageSize':'ページサイズ','form.searchPage':'ページ内検索','form.actionExample':'例: message.send','form.searchAudit':'読み込み済み行を絞り込む（アクター、操作、リソース、詳細）','form.direction':'方向','form.status':'状態','form.agentIdPrefix':'エージェント ID またはプレフィックス','form.sessionId':'セッション ID','form.searchBody':'本文の全文検索','form.priorityFilters':'優先度フィルター','form.listView':'リスト表示','form.enabledReadOnly':'有効状態は読み取り専用','form.enabledReadOnlyAria':'有効（読み取り専用）','form.actions':'操作','form.closeDrawer':'ドロワーを閉じる','form.rotateToken':'トークンをローテーション','form.revokeAccess':'アクセスを取り消す','form.grantAccess':'アクセスを許可','form.shownOnce':'一度だけ表示 — 今すぐコピーしてください','form.newToken':(p:MessageParams)=>`${p.name??''} の新しい token`,'form.rotatedToken':'ローテーション済み boss token',
 'form.createdGroup':(p:MessageParams)=>`グループ ${p.name??''} を作成しました`,'form.createdBoss':(p:MessageParams)=>`boss ${p.name??''} を作成しました`,'form.tokenRotated':(p:MessageParams)=>`${p.name??''} の token をローテーションしました`,'form.forwarded':(p:MessageParams)=>`${p.channel??''} に転送しました`,'form.reacted':(p:MessageParams)=>`${p.emoji??''} にリアクションしました`,'form.broadcastDelivered':(p:MessageParams)=>`${n(p)} エージェントにブロードキャストを配信しました`,'form.doctor':(p:MessageParams)=>`Doctor: ${p.label??''}`,'form.accessGranted':'アクセスを許可しました','form.accessRevoked':'アクセスを取り消しました','form.groupDeleted':'グループを削除しました','form.memberAdded':'メンバーを追加しました','form.memberRemoved':'メンバーを削除しました','form.routingCreated':'ルーティングルールを作成しました','form.routingDeleted':'ルーティングルールを削除しました','form.agentConfigSaved':'エージェント設定を保存しました',
 'status.healthy':'正常','status.degraded':'低下','status.unhealthy':'異常','status.dbOk':'DB 正常','status.dbFail':'DB 失敗','status.apiOk':'API 正常','status.apiFail':'API 失敗','channel.configured':'設定済み','channel.missing':'未設定','channel.on':'オン','channel.off':'オフ','channel.cliNote':'チャンネルの秘密情報は hiboss CLI で管理されます — この画面は読み取り専用です。','status.blocking':'ブロック中','status.noStatusText':'状態テキストなし','status.noSession':'セッションなし','status.never':'なし','status.sent':'送信済み','status.delivered':'配信済み','status.read':'既読','status.replied':'返信済み','status.expired':'期限切れ','session.working':'実行中','session.waiting':'待機中','session.blocked':'ブロック中','session.completed':'完了','session.idle':'アイドル','priority.critical':'重大','priority.high':'高','priority.normal':'通常','priority.low':'低','direction.agentToBoss':'エージェント → Boss','direction.bossToAgent':'Boss → エージェント','direction.agentToAgent':'エージェント → エージェント','role.admin':'管理者','role.manager':'マネージャー','role.viewer':'閲覧者',
 'pager.range':(p:MessageParams)=>`${p.from??0}–${p.to??0} / ${p.total??0}`,'pager.empty':'0 / 0','pager.serverPage':(p:MessageParams)=>`サーバーページ ${p.page??0}`,'pager.limit':(p:MessageParams)=>`${p.limit??0} 件ずつ`,'pager.showing':(p:MessageParams)=>`検索後 ${p.count??0} 件を表示`,'time.secondsAgo':(p:MessageParams)=>`${p.count??0} 秒前`,'time.minutesAgo':(p:MessageParams)=>`${p.count??0} 分前`,'time.hoursAgo':(p:MessageParams)=>`${p.count??0} 時間前`,'time.daysAgo':(p:MessageParams)=>`${p.count??0} 日前`,'time.justNow':'たった今'
 , 'common.messageSummary':(p:MessageParams)=>`${p.total??0} 件中 ${p.loaded??0} 件を読み込み済み · 絞り込み ${p.filtered??0} 件 · ${p.mode??''}`,'form.sendCommandNote':(p:MessageParams)=>`近日対応 — boss API にはセッション送信エンドポイントがまだありません（例: POST ${p.endpoint??''} が必要です）。`,'form.invalidPriority':'デフォルト優先度が無効です','form.invalidRateLimit':'レート制限は 0 以上の整数または空にしてください','form.invalidChannel':'ルーティングのチャンネルが無効です','pager.summary':(p:MessageParams)=>`サーバーページ ${p.page??0} · 1ページ ${p.limit??0} 件 · 合計 ${p.total??0} 件${p.showing===undefined?'':` · 検索後 ${p.showing} 件を表示`}`,
} satisfies LocaleDictionary<MessageKey>;
