/**
 * UNREVIEWED MACHINE DRAFT — Korean web-console dictionary.
 * Exports: koMessages, checked against the English message key set.
 * Deps: plural helper and the shared locale contracts.
 */
import { plural } from './plural';
import type { LocaleDictionary, MessageParams } from './types';
import type { MessageKey } from './en';
const n = (p: MessageParams): number => Number(p.count ?? 0);
export const koMessages = {
 'form.noDescription':'설명 없음','form.copy':'복사','form.copied':'복사됨',
 'app.title':'hiboss 콘솔','app.loading':'콘솔을 불러오는 중…','brand.console':'콘솔','brand.subtitle':'boss 서버에 연결','language.label':'언어','language.en':'English','language.zh':'중국어 간체','language.ja':'일본어','language.ko':'한국어',
 'nav.aria':'콘솔 모듈','nav.dashboard':'대시보드','nav.messages':'메시지','nav.sessions':'세션','nav.agents':'에이전트','nav.groups':'그룹','nav.bosses':'Boss 및 액세스','nav.routing':'라우팅','nav.channels':'채널','nav.audit':'감사','nav.system':'시스템 / Doctor',
 'nav.short.dashboard':'개요','nav.short.messages':'메시지','nav.short.sessions':'세션','nav.short.agents':'에이전트','nav.short.groups':'그룹','nav.short.bosses':'액세스','nav.short.routing':'라우팅','nav.short.channels':'채널','nav.short.audit':'감사','nav.short.system':'시스템',
 'top.connected':'연결됨','top.offline':'오프라인','top.signOut':'로그아웃','common.refresh':'새로 고침','common.retry':'다시 시도','common.close':'닫기','common.dismiss':'닫기','common.cancel':'취소','common.create':'생성','common.creating':'생성 중…','common.save':'설정 저장','common.saving':'저장 중…','common.apply':'적용','common.delete':'삭제','common.deleting':'삭제 중…','common.add':'추가','common.remove':'제거','common.previous':'이전','common.next':'다음','common.nothing':'아직 내용이 없습니다','common.all':'전체','common.dataWillAppear':'에이전트가 보고를 시작하면 데이터가 표시됩니다.','common.requestFailed':'요청 실패','common.never':'없음','common.unknown':'알 수 없음','common.optional':'선택 사항','common.selectAgent':'에이전트 선택…','common.selectGroup':'그룹 선택…','common.selectOwner':'소유자 선택…','common.selectTarget':'대상 선택','common.noLimit':'제한 없음',
 'common.members':(p:MessageParams)=>plural(n(p),'ko',{other:`멤버 ${n(p)}명`}),'common.agents':(p:MessageParams)=>plural(n(p),'ko',{other:`에이전트 ${n(p)}명`}),'common.channels':(p:MessageParams)=>plural(n(p),'ko',{other:`채널 ${n(p)}개`}),'common.loaded':(p:MessageParams)=>`${p.total??0}개 중 ${p.loaded??0}개 로드됨`,'common.filtered':(p:MessageParams)=>`필터 결과 ${p.count??0}개`,'common.latestDirections':'최근 10개 · 모든 방향',
 'page.dashboard':'대시보드','page.dashboardSub':'개요 — 실시간 KPI, 채널 상태, 최근 트래픽','page.priorityDistribution':'우선순위 분포','page.last24h':'최근 24시간','page.sessionStatus':'세션 상태','page.seenLast24h':'최근 24시간 내 확인','page.channelHealth':'채널 상태','page.configuredPaths':'구성된 전송 경로','page.recentMessages':'최근 메시지','page.noRecentMessages':'최근 메시지가 없습니다','page.noRecentMessagesDetail':'에이전트가 업데이트를 보내면 여기에 표시됩니다.','page.activeSessions':'활성 세션','page.working':(p:MessageParams)=>`${p.count??0}개 작업 중`,'page.pendingDecisions':'대기 중인 결정','page.pendingDecisionsHint':'선택을 기다리는 옵션 메시지','page.blockingPending':'차단 대기','page.blockingPendingHint':'사용자의 처리를 기다리는 에이전트','page.unread1h':'읽지 않음 (1시간)','page.unread1hHint':'에이전트 → boss, 아직 읽지 않음',
 'page.agents':'에이전트','page.agentsSub':'에이전트 — 목록, 식별 정보 및 편집 가능한 구성','page.noAgents':'에이전트가 없습니다','page.noAgentsDetail':'이 boss가 액세스할 수 있는 에이전트가 권한 부여 후 표시됩니다.','page.groups':'그룹','page.groupsSub':'에이전트 그룹 — 그룹 목록 및 전체 그룹 브로드캐스트','page.noGroups':'아직 그룹이 없습니다','page.noGroupsDetail':'액세스 가능한 에이전트가 소유한 그룹을 만들어 시작하세요.','page.bosses':'Boss 및 액세스','page.bossesSub':'액세스 — boss 역할, 채널 바인딩 및 에이전트 액세스 매트릭스','page.noBosses':'아직 boss가 없습니다','page.noBossesDetail':'역할, 바인딩 및 에이전트 액세스를 관리할 boss를 생성하세요.','page.noAgentsInScope':'범위 내 에이전트가 없습니다 — 액세스 가능한 에이전트가 있으면 권한 열이 표시됩니다.',
 'page.routing':'라우팅','page.routingSub':'라우팅 규칙 — 우선순위 표 및 정규식 매처','page.noRouting':'라우팅 규칙이 없습니다','page.noRoutingDetail':'정규식 라우팅 규칙을 추가하거나 에이전트가 정의할 때까지 기다리세요.','page.channels':'채널','page.channelsSub':'채널 — 에이전트별 연결 보드','page.noChannels':'구성된 채널이 없습니다','page.noChannelsDetail':'hiboss CLI에서 Discord, Telegram, 이메일 또는 API 전송을 구성하세요. 비밀 정보는 여기에 표시되지 않습니다.','page.audit':'감사','page.auditSub':'감사 — 검색 가능한 작업 및 전송 로그','page.noAudit':'감사 항목이 없습니다','page.noAuditDetail':'에이전트와 boss가 시스템에서 작업하면 여기에 표시됩니다.','page.noAuditSearch':'검색과 일치하는 행이 없습니다','page.noAuditSearchDetail':'페이지 검색을 지우거나 행위자/작업 필터를 넓힌 후 적용하세요.',
 'page.sessions':'세션','page.sessionsSub':'세션 — 상태별 에이전트 세션 칸반','page.noSessions':'세션이 없습니다','page.noSessionsDetail':'활성 에이전트 세션은 보고되면 여기에 표시됩니다.','page.messages':'메시지','page.messagesSub':'메시지 — 전체 스트림, 필터, 세션 그룹화 및 상세 드로어','page.noMessageMatch':'일치하는 메시지가 없습니다','page.noMessageMatchDetail':'방향을 넓히거나 우선순위 칩을 지우거나 다른 용어를 검색해 보세요.','page.loadMore':(p:MessageParams)=>`더 불러오기 (${p.count??0})`,'page.bySession':'세션별','page.flat':'평면','page.checking':'확인 중…','page.rerunChecks':'검사 다시 실행','page.system':'시스템 / Doctor','page.systemSub':'시스템 — 연결 자체 검사, 채널 상태 및 실시간 통계','page.seenRecently':'최근 확인','page.noChannelRows':'채널 행이 반환되지 않았습니다.',
 'connect.serverUrl':'서버 URL','connect.bossToken':'Boss token','connect.connect':'연결','connect.connecting':'연결 중…','connect.storedHint':'Token은 이 브라우저에만 저장됩니다 (localStorage).','form.name':'이름','form.role':'역할','form.telegramId':'Telegram ID','form.discordId':'Discord ID','form.description':'설명','form.ownerAgent':'소유자 에이전트','form.targetAgent':'대상 에이전트','form.channel':'채널','form.pattern':'패턴','form.regexPattern':'정규식 패턴','form.priority':'우선순위','form.createBoss':'boss 생성','form.createGroup':'그룹 생성','form.addRule':'규칙 추가','form.bossName':'Boss 이름','form.groupName':'그룹 이름','form.noAgentsGroup':'사용 가능한 에이전트가 없습니다 — 에이전트를 연결한 후 그룹을 생성하세요.','form.noAgentsRule':'사용 가능한 에이전트가 없습니다 — 액세스 권한을 부여한 후 규칙을 추가하세요.','form.createRule':'생성','form.addRoute':'라우트 추가','form.removeRoute':'라우트 제거',
 'form.agentConfig':'에이전트 구성','form.config':'구성','form.configDetail':'이 에이전트의 기본 우선순위, 속도 제한 및 채널 라우팅입니다.','form.defaultPriority':'기본 우선순위','form.rateLimit':'속도 제한','form.channelRouting':'채널 라우팅','form.noRoutes':'라우트가 없습니다 — 키가 채널에 매핑됩니다 (예: critical → discord).','form.saveConfig':'구성 저장','form.replyEmpty':'답장 본문이 비어 있습니다','form.writeReply':'답장 작성…','form.sendReply':'답장 보내기','form.forward':'전달','form.sending':'보내는 중…','form.sendBroadcast':'브로드캐스트 보내기','form.broadcasting':'보내는 중…','form.broadcastTo':(p:MessageParams)=>`${p.name??''}에 브로드캐스트…`,'form.writeBroadcast':'그룹 브로드캐스트 작성…','form.broadcast':'브로드캐스트','form.broadcastDetail':'그룹 브로드캐스트 — 그룹의 모든 멤버에게 메시지 보내기',
 'form.members':'멤버','form.memberEditor':'그룹 멤버 편집기','form.addMember':'멤버 추가','form.removeMember':'멤버 제거','form.hideMembers':'멤버 숨기기','form.editMembers':'멤버 편집','form.deleteGroupConfirm':(p:MessageParams)=>`그룹 “${p.name??''}”을(를) 삭제할까요? 되돌릴 수 없습니다.`,'form.endpointUnavailable':'엔드포인트를 사용할 수 없음','form.sendCommand':'명령 보내기','form.sendCommandDetail':'곧 지원 예정 — boss API에 세션 전송 엔드포인트가 아직 없습니다 (예: 필요','form.recentMessages':'최근 메시지','form.sessionNoTraffic':'이 세션에는 최근 트래픽이 없습니다.','form.messageOptions':'메시지 옵션','form.options':'옵션','form.optionsExpired':'옵션 만료','form.react':'반응','form.messageDetail':'메시지 상세','form.sessionDetail':'세션 상세','form.agentDetail':'에이전트 상세','form.created':'생성됨','form.updated':'업데이트됨','form.expires':'만료','form.lastSeen':'최근 확인','form.started':'시작됨','form.branch':'브랜치','form.cwd':'작업 디렉터리','form.id':'ID','form.authenticatedBoss':'인증된 boss','form.serverTime':'서버 시간','form.apiLatency':'API 지연','form.notVerified':'확인되지 않음','form.database':'데이터베이스','form.apiMe':'API /me','form.auditLog':'감사 로그','form.auditPagination':'감사 로그 페이지 매김','form.when':'시간','form.actor':'행위자','form.action':'작업','form.resource':'리소스','form.details':'상세',
 'form.actorType':'행위자 유형','form.pageSize':'페이지 크기','form.searchPage':'페이지 검색','form.actionExample':'예: message.send','form.searchAudit':'로드된 행 필터 (행위자, 작업, 리소스, 상세)','form.direction':'방향','form.status':'상태','form.agentIdPrefix':'에이전트 ID 또는 접두사','form.sessionId':'세션 ID','form.searchBody':'본문 전문 검색','form.priorityFilters':'우선순위 필터','form.listView':'목록 보기','form.enabledReadOnly':'활성화는 읽기 전용','form.enabledReadOnlyAria':'활성화 (읽기 전용)','form.actions':'작업','form.closeDrawer':'드로어 닫기','form.rotateToken':'토큰 교체','form.revokeAccess':'액세스 취소','form.grantAccess':'액세스 허용','form.shownOnce':'한 번만 표시 — 지금 복사하세요','form.newToken':(p:MessageParams)=>`${p.name??''}의 새 token`,'form.rotatedToken':'교체된 boss token',
 'form.createdGroup':(p:MessageParams)=>`그룹 ${p.name??''} 생성됨`,'form.createdBoss':(p:MessageParams)=>`boss ${p.name??''} 생성됨`,'form.tokenRotated':(p:MessageParams)=>`${p.name??''}의 token 교체됨`,'form.forwarded':(p:MessageParams)=>`${p.channel??''}(으)로 전달됨`,'form.reacted':(p:MessageParams)=>`${p.emoji??''}에 반응함`,'form.broadcastDelivered':(p:MessageParams)=>`${n(p)}명의 에이전트에게 브로드캐스트 전달됨`,'form.doctor':(p:MessageParams)=>`Doctor: ${p.label??''}`,'form.accessGranted':'액세스 허용됨','form.accessRevoked':'액세스 취소됨','form.groupDeleted':'그룹 삭제됨','form.memberAdded':'멤버 추가됨','form.memberRemoved':'멤버 제거됨','form.routingCreated':'라우팅 규칙 생성됨','form.routingDeleted':'라우팅 규칙 삭제됨','form.agentConfigSaved':'에이전트 구성 저장됨',
 'status.healthy':'정상','status.degraded':'저하됨','status.unhealthy':'비정상','status.dbOk':'DB 정상','status.dbFail':'DB 실패','status.apiOk':'API 정상','status.apiFail':'API 실패','channel.configured':'구성됨','channel.missing':'누락됨','channel.on':'켜짐','channel.off':'꺼짐','channel.cliNote':'채널 비밀 정보는 hiboss CLI에서 관리됩니다 — 이 화면은 읽기 전용입니다.','status.blocking':'차단 중','status.noStatusText':'상태 텍스트 없음','status.noSession':'세션 없음','status.never':'없음','status.sent':'전송됨','status.delivered':'배달됨','status.read':'읽음','status.replied':'답장됨','status.expired':'만료됨','session.working':'작업 중','session.waiting':'대기 중','session.blocked':'차단됨','session.completed':'완료됨','session.idle':'유휴','priority.critical':'긴급','priority.high':'높음','priority.normal':'보통','priority.low':'낮음','direction.agentToBoss':'에이전트 → Boss','direction.bossToAgent':'Boss → 에이전트','direction.agentToAgent':'에이전트 → 에이전트','role.admin':'관리자','role.manager':'매니저','role.viewer':'뷰어',
 'pager.range':(p:MessageParams)=>`${p.from??0}–${p.to??0} / 총 ${p.total??0}`,'pager.empty':'0 / 0','pager.serverPage':(p:MessageParams)=>`서버 ${p.page??0}페이지`,'pager.limit':(p:MessageParams)=>`페이지당 ${p.limit??0}개`,'pager.showing':(p:MessageParams)=>`검색 후 ${p.count??0}개 표시`,'time.secondsAgo':(p:MessageParams)=>`${p.count??0}초 전`,'time.minutesAgo':(p:MessageParams)=>`${p.count??0}분 전`,'time.hoursAgo':(p:MessageParams)=>`${p.count??0}시간 전`,'time.daysAgo':(p:MessageParams)=>`${p.count??0}일 전`,'time.justNow':'방금 전'
 , 'common.messageSummary':(p:MessageParams)=>`${p.total??0}개 중 ${p.loaded??0}개 로드됨 · 필터 결과 ${p.filtered??0}개 · ${p.mode??''}`,'form.sendCommandNote':(p:MessageParams)=>`곧 지원 예정 — boss API에 세션 전송 엔드포인트가 아직 없습니다 (예: POST ${p.endpoint??''} 필요).`,'form.invalidPriority':'기본 우선순위가 잘못되었습니다','form.invalidRateLimit':'속도 제한은 음이 아닌 정수 또는 빈 값이어야 합니다','form.invalidChannel':'라우팅의 채널이 잘못되었습니다','pager.summary':(p:MessageParams)=>`서버 ${p.page??0}페이지 · 페이지당 ${p.limit??0}개 · 총 ${p.total??0}개${p.showing===undefined?'':` · 검색 후 ${p.showing}개 표시`}`,
} satisfies LocaleDictionary<MessageKey>;
