/**
 * Simplified Chinese dictionary for the web console.
 * Exports: zhMessages, checked against the English message key set.
 * Deps: plural helper and the shared locale contracts.
 */
import { plural } from './plural';
import type { LocaleDictionary, MessageParams } from './types';
import type { MessageKey } from './en';
const n = (p: MessageParams): number => Number(p.count ?? 0);
export const zhMessages = {
 'form.noDescription':'暂无描述','form.copy':'复制','form.copied':'已复制',
 'app.title':'hiboss 指挥台','app.loading':'正在加载控制台…','brand.console':'控制台','brand.subtitle':'连接到你的 boss 服务器','language.label':'语言','language.en':'English','language.zh':'简体中文','language.ja':'日本語','language.ko':'한국어',
 'nav.aria':'控制台模块','nav.dashboard':'总览','nav.messages':'消息','nav.sessions':'会话','nav.agents':'智能体','nav.groups':'分组','nav.bosses':'Boss 与权限','nav.routing':'路由','nav.channels':'渠道','nav.audit':'审计','nav.system':'系统 / Doctor',
 'nav.short.dashboard':'总览','nav.short.messages':'消息','nav.short.sessions':'会话','nav.short.agents':'智能体','nav.short.groups':'分组','nav.short.bosses':'权限','nav.short.routing':'路由','nav.short.channels':'渠道','nav.short.audit':'审计','nav.short.system':'系统',
 'top.connected':'已连接','top.offline':'离线','top.signOut':'退出登录','common.refresh':'刷新','common.retry':'重试','common.close':'关闭','common.dismiss':'忽略','common.cancel':'取消','common.create':'创建','common.creating':'创建中…','common.save':'保存配置','common.saving':'保存中…','common.apply':'应用','common.delete':'删除','common.deleting':'删除中…','common.add':'添加','common.remove':'移除','common.previous':'上一页','common.next':'下一页','common.nothing':'暂无内容','common.all':'全部','common.dataWillAppear':'智能体开始上报后，数据会显示在这里。','common.requestFailed':'请求失败','common.never':'从未','common.unknown':'未知','common.optional':'可选','common.selectAgent':'选择智能体…','common.selectGroup':'选择分组…','common.selectOwner':'选择所有者…','common.selectTarget':'选择目标','common.noLimit':'无限制',
 'common.members':(p:MessageParams)=>plural(n(p),'zh-CN',{other:`${n(p)} 个成员`}),'common.agents':(p:MessageParams)=>plural(n(p),'zh-CN',{other:`${n(p)} 个智能体`}),'common.channels':(p:MessageParams)=>plural(n(p),'zh-CN',{other:`${n(p)} 个渠道`}),'common.loaded':(p:MessageParams)=>`已加载 ${p.loaded??0}/${p.total??0}`,'common.filtered':(p:MessageParams)=>`筛选后 ${p.count??0} 条`,'common.latestDirections':'最新 10 条 · 所有方向',
 'page.dashboard':'总览','page.dashboardSub':'总览 — 实时指标、渠道健康度、近期流量','page.priorityDistribution':'优先级分布','page.last24h':'最近 24 小时','page.sessionStatus':'会话状态','page.seenLast24h':'最近 24 小时内出现','page.channelHealth':'渠道健康度','page.configuredPaths':'已配置的投递路径','page.recentMessages':'最近消息','page.noRecentMessages':'暂无最近消息','page.noRecentMessagesDetail':'智能体发送更新后，会显示在这里。','page.activeSessions':'活跃会话','page.working':(p:MessageParams)=>`${p.count??0} 个工作中`,'page.pendingDecisions':'待处理决策','page.pendingDecisionsHint':'等待选择的选项消息','page.blockingPending':'待处理阻塞','page.blockingPendingHint':'等待你处理的智能体','page.unread1h':'未读（1 小时）','page.unread1hHint':'智能体 → boss，尚未阅读',
 'page.agents':'智能体','page.agentsSub':'智能体 — 列表、身份和可编辑配置','page.noAgents':'暂无智能体','page.noAgentsDetail':'此 boss 可访问的智能体将在授权后显示。','page.groups':'分组','page.groupsSub':'智能体分组 — 分组列表和全组广播','page.noGroups':'暂无分组','page.noGroupsDetail':'创建一个由可访问智能体拥有的分组即可开始。','page.bosses':'Boss 与权限','page.bossesSub':'权限 — boss 角色、渠道绑定和智能体访问矩阵','page.noBosses':'暂无 boss','page.noBossesDetail':'创建 boss 以管理角色、绑定和智能体访问权限。','page.noAgentsInScope':'当前范围内暂无智能体 — 可访问智能体后会出现授权列。',
 'page.routing':'路由','page.routingSub':'路由规则 — 优先级表和正则匹配器','page.noRouting':'暂无路由规则','page.noRoutingDetail':'添加正则路由规则，或等待智能体定义规则。','page.channels':'渠道','page.channelsSub':'渠道 — 按智能体显示的连接面板','page.noChannels':'未配置渠道','page.noChannelsDetail':'通过 hiboss CLI 配置 Discord、Telegram、邮件或 API 投递。密钥不会显示在这里。','page.audit':'审计','page.auditSub':'审计 — 可搜索的操作和投递日志','page.noAudit':'暂无审计记录','page.noAuditDetail':'智能体和 boss 操作系统后，记录会显示在这里。','page.noAuditSearch':'没有匹配的行','page.noAuditSearchDetail':'清除页面搜索或放宽操作者/操作筛选，然后点击应用。',
 'page.sessions':'会话','page.sessionsSub':'会话 — 按状态排列的智能体会话看板','page.noSessions':'暂无会话','page.noSessionsDetail':'活跃智能体上报后，会话会显示在这里。','page.messages':'消息','page.messagesSub':'消息 — 全量流、筛选、会话分组和详情抽屉','page.noMessageMatch':'没有匹配的消息','page.noMessageMatchDetail':'尝试放宽方向、清除优先级标签，或搜索其他词。','page.loadMore':(p:MessageParams)=>`加载更多（${p.count??0}）`,'page.bySession':'按会话','page.flat':'平铺','page.checking':'检查中…','page.rerunChecks':'重新检查','page.system':'系统 / Doctor','page.systemSub':'系统 — 连接自检、渠道健康度和实时统计','page.seenRecently':'最近出现','page.noChannelRows':'未返回渠道记录。',
 'connect.serverUrl':'服务器 URL','connect.bossToken':'Boss token','connect.connect':'连接','connect.connecting':'连接中…','connect.storedHint':'Token 仅存储在此浏览器中（localStorage）。','form.name':'名称','form.role':'角色','form.telegramId':'Telegram ID','form.discordId':'Discord ID','form.description':'描述','form.ownerAgent':'所有者智能体','form.targetAgent':'目标智能体','form.channel':'渠道','form.pattern':'模式','form.regexPattern':'正则模式','form.priority':'优先级','form.createBoss':'创建 boss','form.createGroup':'创建分组','form.addRule':'添加规则','form.bossName':'Boss 名称','form.groupName':'分组名称','form.noAgentsGroup':'没有可用智能体 — 连接智能体后才能创建分组。','form.noAgentsRule':'没有可用智能体 — 授权后才能添加规则。','form.createRule':'创建','form.addRoute':'添加路由','form.removeRoute':'移除路由',
 'form.agentConfig':'智能体配置','form.config':'配置','form.configDetail':'此智能体的默认优先级、速率限制和渠道路由。','form.defaultPriority':'默认优先级','form.rateLimit':'速率限制','form.channelRouting':'渠道路由','form.noRoutes':'暂无路由 — 键会映射到渠道（例如 critical → discord）。','form.saveConfig':'保存配置','form.replyEmpty':'回复内容为空','form.writeReply':'写一条回复…','form.sendReply':'发送回复','form.forward':'转发','form.sending':'发送中…','form.sendBroadcast':'发送广播','form.broadcasting':'发送中…','form.broadcastTo':(p:MessageParams)=>`广播给 ${p.name??''}…`,'form.writeBroadcast':'编写全组广播…','form.broadcast':'广播','form.broadcastDetail':'全组广播 — 向分组的每位成员发送消息',
 'form.members':'成员','form.memberEditor':'分组成员编辑器','form.addMember':'添加成员','form.removeMember':'移除成员','form.hideMembers':'隐藏成员','form.editMembers':'编辑成员','form.deleteGroupConfirm':(p:MessageParams)=>`删除分组“${p.name??''}”？此操作无法撤销。`,'form.endpointUnavailable':'端点不可用','form.sendCommand':'发送命令','form.sendCommandDetail':'即将支持 — boss API 尚无发送到会话的端点（例如需要','form.recentMessages':'最近消息','form.sessionNoTraffic':'此会话近期没有流量。','form.messageOptions':'消息选项','form.options':'选项','form.optionsExpired':'选项已过期','form.react':'回应','form.messageDetail':'消息详情','form.sessionDetail':'会话详情','form.agentDetail':'智能体详情','form.created':'创建时间','form.updated':'更新时间','form.expires':'过期时间','form.lastSeen':'最近出现','form.started':'开始时间','form.branch':'分支','form.cwd':'工作目录','form.id':'ID','form.authenticatedBoss':'已认证 boss','form.serverTime':'服务器时间','form.apiLatency':'API 延迟','form.notVerified':'未验证','form.database':'数据库','form.apiMe':'API /me','form.auditLog':'审计日志','form.auditPagination':'审计日志分页','form.when':'时间','form.actor':'操作者','form.action':'操作','form.resource':'资源','form.details':'详情',
 'form.actorType':'操作者类型','form.pageSize':'页面大小','form.searchPage':'搜索本页','form.actionExample':'例如 message.send','form.searchAudit':'筛选已加载行（操作者、操作、资源、详情）','form.direction':'方向','form.status':'状态','form.agentIdPrefix':'智能体 ID 或前缀','form.sessionId':'会话 ID','form.searchBody':'全文搜索消息正文','form.priorityFilters':'优先级筛选','form.listView':'列表视图','form.enabledReadOnly':'启用状态只读','form.enabledReadOnlyAria':'启用（只读）','form.actions':'操作','form.closeDrawer':'关闭抽屉','form.rotateToken':'轮换 token','form.revokeAccess':'撤销访问','form.grantAccess':'授予访问','form.shownOnce':'仅显示一次 — 请立即复制','form.newToken':(p:MessageParams)=>`${p.name??''} 的新 token`,'form.rotatedToken':'已轮换的 boss token',
 'form.createdGroup':(p:MessageParams)=>`已创建分组 ${p.name??''}`,'form.createdBoss':(p:MessageParams)=>`已创建 boss ${p.name??''}`,'form.tokenRotated':(p:MessageParams)=>`已为 ${p.name??''} 轮换 token`,'form.forwarded':(p:MessageParams)=>`已转发到 ${p.channel??''}`,'form.reacted':(p:MessageParams)=>`已回应 ${p.emoji??''}`,'form.broadcastDelivered':(p:MessageParams)=>`${n(p)} 个智能体已收到广播`,'form.doctor':(p:MessageParams)=>`Doctor：${p.label??''}`,'form.accessGranted':'已授予访问权限','form.accessRevoked':'已撤销访问权限','form.groupDeleted':'分组已删除','form.memberAdded':'成员已添加','form.memberRemoved':'成员已移除','form.routingCreated':'路由规则已创建','form.routingDeleted':'路由规则已删除','form.agentConfigSaved':'智能体配置已保存',
 'status.healthy':'健康','status.degraded':'降级','status.unhealthy':'不健康','status.dbOk':'数据库正常','status.dbFail':'数据库失败','status.apiOk':'API 正常','status.apiFail':'API 失败','channel.configured':'已配置','channel.missing':'缺失','channel.on':'开启','channel.off':'关闭','channel.cliNote':'渠道密钥通过 hiboss CLI 管理 — 此视图为只读。','status.blocking':'阻塞','status.noStatusText':'暂无状态文本','status.noSession':'无会话','status.never':'从未','status.sent':'已发送','status.delivered':'已投递','status.read':'已读','status.replied':'已回复','status.expired':'已过期','session.working':'工作中','session.waiting':'等待中','session.blocked':'阻塞','session.completed':'已完成','session.idle':'空闲','priority.critical':'严重','priority.high':'高','priority.normal':'普通','priority.low':'低','direction.agentToBoss':'智能体 → Boss','direction.bossToAgent':'Boss → 智能体','direction.agentToAgent':'智能体 → 智能体','role.admin':'管理员','role.manager':'管理者','role.viewer':'查看者',
 'pager.range':(p:MessageParams)=>`${p.from??0}–${p.to??0}，共 ${p.total??0}`,'pager.empty':'0，共 0','pager.serverPage':(p:MessageParams)=>`服务器第 ${p.page??0} 页`,'pager.limit':(p:MessageParams)=>`每页 ${p.limit??0} 条`,'pager.showing':(p:MessageParams)=>`搜索后显示 ${p.count??0} 条`,'time.secondsAgo':(p:MessageParams)=>`${p.count??0} 秒前`,'time.minutesAgo':(p:MessageParams)=>`${p.count??0} 分钟前`,'time.hoursAgo':(p:MessageParams)=>`${p.count??0} 小时前`,'time.daysAgo':(p:MessageParams)=>`${p.count??0} 天前`,'time.justNow':'刚刚'
 , 'common.messageSummary':(p:MessageParams)=>`已加载 ${p.loaded??0}/${p.total??0} · 筛选后 ${p.filtered??0} 条 · ${p.mode??''}`,'form.sendCommandNote':(p:MessageParams)=>`即将支持 — boss API 尚无发送到会话的端点（例如需要 POST ${p.endpoint??''}）。`,'form.invalidPriority':'默认优先级无效','form.invalidRateLimit':'速率限制必须是非负整数或为空','form.invalidChannel':'路由中的渠道无效','pager.summary':(p:MessageParams)=>`服务器第 ${p.page??0} 页 · 每页 ${p.limit??0} 条 · 共 ${p.total??0}${p.showing===undefined?'':` · 搜索后显示 ${p.showing} 条`}`,
} satisfies LocaleDictionary<MessageKey>;
